### ISSUE TITLE
localhost/:1 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:8000/example.js

### ISSUE THREAD

**Issue by tarlepp** [TheVelourFog/slush-angular2#5]
I get following after I made `npm start` and open `localhost:8000` URL on my browser:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Uncaught (in promise) Error: XHR error (404 Not Found) loading http://localhost:8000/example.js
    Error loading http://localhost:8000/example.js as "example" from http://localhost:8000/src/boot.ts
    at error (http://localhost:8000/jspm_packages/system.src.js:1028:16)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:8000/jspm_packages/system.src.js:1036:13)
```

How to solve this?

**Comment by Geraldf** [comment]
I am having the same issues. It looks like the .ts files are not compiled to .js files, and therefore it cannot find them. I am trying to get them compiled with gulp-tsc , but I have not been successful yet

**Comment by tarlepp** [comment]
any updates on this?

**Comment by RyanMetin** [comment]
Sorry for the wait on this - I wasn't seeing the same issue. Then I realized the package I was using globally wasn't the same as what was published... Dumb mistake, I know.

The issue was with the System.packages. I had the map configuration as a package itself when it needed to be within the package path.
